// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AltruistRegistryService is an autogenerated mock type for the AltruistRegistryService type
type AltruistRegistryService struct {
	mock.Mock
}

type AltruistRegistryService_Expecter struct {
	mock *mock.Mock
}

func (_m *AltruistRegistryService) EXPECT() *AltruistRegistryService_Expecter {
	return &AltruistRegistryService_Expecter{mock: &_m.Mock}
}

// GetAltruistURL provides a mock function with given fields: chainId
func (_m *AltruistRegistryService) GetAltruistURL(chainId string) (string, bool) {
	ret := _m.Called(chainId)

	if len(ret) == 0 {
		panic("no return value specified for GetAltruistURL")
	}

	var r0 string
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (string, bool)); ok {
		return rf(chainId)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(chainId)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(chainId)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// AltruistRegistryService_GetAltruistURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAltruistURL'
type AltruistRegistryService_GetAltruistURL_Call struct {
	*mock.Call
}

// GetAltruistURL is a helper method to define mock.On call
//   - chainId string
func (_e *AltruistRegistryService_Expecter) GetAltruistURL(chainId interface{}) *AltruistRegistryService_GetAltruistURL_Call {
	return &AltruistRegistryService_GetAltruistURL_Call{Call: _e.mock.On("GetAltruistURL", chainId)}
}

func (_c *AltruistRegistryService_GetAltruistURL_Call) Run(run func(chainId string)) *AltruistRegistryService_GetAltruistURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *AltruistRegistryService_GetAltruistURL_Call) Return(_a0 string, _a1 bool) *AltruistRegistryService_GetAltruistURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AltruistRegistryService_GetAltruistURL_Call) RunAndReturn(run func(string) (string, bool)) *AltruistRegistryService_GetAltruistURL_Call {
	_c.Call.Return(run)
	return _c
}

// NewAltruistRegistryService creates a new instance of AltruistRegistryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAltruistRegistryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AltruistRegistryService {
	mock := &AltruistRegistryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
